# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

# NAS 쪽에 Azure data center 쪽 IP 대역대 허용해주어야 한다.

name: Java CI with Gradle

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
#    - name: Build with Gradle
#      run: ./gradlew bootJar
#    - name: Grant 777 permission
#      run: chmod -R 777 ./build/libs
    - name: Grant 777 permission
      run: |
        chmod 777 ./http
        ls -al
        chmod -R 777 ./http
        ls -al ./http/
    - name: Copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "./http/pet.http"
        target: "/volume1/docker/deploy/sample/"

#      uses: garygrossgarten/github-action-scp@release
#      with:
#        host: ${{ secrets.HOST }}
#        port: ${{ secrets.PORT }}
#        username: ${{ secrets.USERNAME }}
#        password: ${{ secrets.PASSWORD }}
##        local: ./build/libs/springboot-web-basis-1.0.0.jar
#        local: ./http/pet.http
#        remote: /volume1/docker/deploy/sample/ # NAS 경로
